---
title: "p8105_hw1_xc2610"
author: "Xuanhe Chen"
date: 2019-09-21
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

Problem 1

```{r df_create}
set.seed(5)

random_df = tibble(
  val = rnorm(10, sd = .5),
  vec_logical = c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
  vec_char = c("A", "B", "C", "D", "E", "F", "G", "H", "I", "J"),
  vec_factor = factor(c("pro", "con", "non", "non", "con", "pro", "con", "non", "pro", "non"))
)

## show(random_df)

random_df$vec_logical <- ifelse(random_df$val < 0, FALSE, TRUE)

## show(random_df)
```


```{r mean}
mean(pull(random_df, val))
mean(pull(random_df, vec_logical))
mean(pull(random_df, vec_char))
mean(pull(random_df, vec_factor))
```
 

```{r as.numeric}
as.numeric(pull(random_df, vec_factor))
```
Problem 2
```{r penguins}
data("penguins", package = "palmerpenguins")
names(penguins)
#view(penguins)
head(penguins)
nrow(penguins)
ncol(penguins)
## skimr::skim(penguins)
penguins$flipper_length_mm [is.na(penguins$flipper_length_mm)] <- 0
head(penguins)
mean(pull(penguins, flipper_length_mm))
```
```{r scatter}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
## ggsave("scatter_HW1_P2.pdf", height = 4, width = 6)
```